/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.88
 * Generated at: 2023-05-04 08:35:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1682046340358L));
    _jspx_dependants.put("jar:file:/D:/java/java_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DemoSpringMVC/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Trang chủ</title>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- \r\n");
      out.write("Body Section \r\n");
      out.write("-->\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<div id=\"sidebar\" class=\"span3\">\r\n");
      out.write("			<div class=\"well well-small\">\r\n");
      out.write("				<ul class=\"nav nav-list\">\r\n");
      out.write("					");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					<li><a class=\"totalInCart\" href=\"cart.html\"><strong>Đã mua <span class=\"badge badge-warning pull-right\"\r\n");
      out.write("								style=\"line-height: 18px;\">$448.42</span>\r\n");
      out.write("						</strong></a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"well well-small alert alert-warning cntr\">\r\n");
      out.write("				<h2>50% Discount</h2>\r\n");
      out.write("				<p>\r\n");
      out.write("					only valid for online order. <br> <br> <a\r\n");
      out.write("						class=\"defaultBtn\" href=\"#\">Click here </a>\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"well well-small\">\r\n");
      out.write("				<a href=\"#\"><img src=\"assets/img/paypal.jpg\"\r\n");
      out.write("					alt=\"payment method paypal\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<a class=\"shopBtn btn-block\" href=\"#\">Upcoming products <br>\r\n");
      out.write("				<small>Click to view</small></a> <br> <br>\r\n");
      out.write("			<ul class=\"nav nav-list promowrapper\">\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"thumbnail\">\r\n");
      out.write("						<a class=\"zoomTool\" href=\"product_details.html\"\r\n");
      out.write("							title=\"add to cart\"><span class=\"icon-search\"></span> QUICK\r\n");
      out.write("							VIEW</a> <img src=\"assets/img/bootstrap-ecommerce-templates.png\"\r\n");
      out.write("							alt=\"bootstrap ecommerce templates\">\r\n");
      out.write("						<div class=\"caption\">\r\n");
      out.write("							<h4>\r\n");
      out.write("								<a class=\"defaultBtn\" href=\"product_details.html\">VIEW</a> <span\r\n");
      out.write("									class=\"pull-right\">$22.00</span>\r\n");
      out.write("							</h4>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li style=\"border: 0\">&nbsp;</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"thumbnail\">\r\n");
      out.write("						<a class=\"zoomTool\" href=\"product_details.html\"\r\n");
      out.write("							title=\"add to cart\"><span class=\"icon-search\"></span> QUICK\r\n");
      out.write("							VIEW</a> <img src=\"assets/img/shopping-cart-template.png\"\r\n");
      out.write("							alt=\"shopping cart template\">\r\n");
      out.write("						<div class=\"caption\">\r\n");
      out.write("							<h4>\r\n");
      out.write("								<a class=\"defaultBtn\" href=\"product_details.html\">VIEW</a> <span\r\n");
      out.write("									class=\"pull-right\">$22.00</span>\r\n");
      out.write("							</h4>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li style=\"border: 0\">&nbsp;</li>\r\n");
      out.write("				<li>\r\n");
      out.write("					<div class=\"thumbnail\">\r\n");
      out.write("						<a class=\"zoomTool\" href=\"product_details.html\"\r\n");
      out.write("							title=\"add to cart\"><span class=\"icon-search\"></span> QUICK\r\n");
      out.write("							VIEW</a> <img src=\"assets/img/bootstrap-template.png\"\r\n");
      out.write("							alt=\"bootstrap template\">\r\n");
      out.write("						<div class=\"caption\">\r\n");
      out.write("							<h4>\r\n");
      out.write("								<a class=\"defaultBtn\" href=\"product_details.html\">VIEW</a> <span\r\n");
      out.write("									class=\"pull-right\">$22.00</span>\r\n");
      out.write("							</h4>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"span9\">\r\n");
      out.write("			<div class=\"well np\">\r\n");
      out.write("				<div id=\"myCarousel\" class=\"carousel slide homCar\">\r\n");
      out.write("					<div class=\"carousel-inner\">\r\n");
      out.write("						");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<a class=\"left carousel-control\" href=\"#myCarousel\"\r\n");
      out.write("					data-slide=\"prev\">&lsaquo;</a> <a class=\"right carousel-control\"\r\n");
      out.write("					href=\"#myCarousel\" data-slide=\"next\">&rsaquo;</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--\r\n");
      out.write("New Products\r\n");
      out.write("-->\r\n");
      out.write("		<div class=\"well well-small\">\r\n");
      out.write("			<h3>New Products</h3>\r\n");
      out.write("			<hr class=\"soften\" />\r\n");
      out.write("			<div class=\"row-fluid\">\r\n");
      out.write("				<div id=\"newProductCar\" class=\"carousel slide\">\r\n");
      out.write("					<div class=\"carousel-inner\">\r\n");
      out.write("						<div class=\"item active\">\r\n");
      out.write("							<ul class=\"thumbnails\">\r\n");
      out.write("								<li class=\"span3\">\r\n");
      out.write("									<div class=\"thumbnail\">\r\n");
      out.write("										<a class=\"zoomTool\" href=\"product_details.html\"\r\n");
      out.write("											title=\"add to cart\"><span class=\"icon-search\"></span>\r\n");
      out.write("											QUICK VIEW</a> <a href=\"#\" class=\"tag\"></a> <a\r\n");
      out.write("											href=\"product_details.html\"><img\r\n");
      out.write("											src=\"assets/img/bootstrap-ring.png\" alt=\"bootstrap-ring\"></a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"span3\">\r\n");
      out.write("									<div class=\"thumbnail\">\r\n");
      out.write("										<a class=\"zoomTool\" href=\"product_details.html\"\r\n");
      out.write("											title=\"add to cart\"><span class=\"icon-search\"></span>\r\n");
      out.write("											QUICK VIEW</a> <a href=\"#\" class=\"tag\"></a> <a\r\n");
      out.write("											href=\"product_details.html\"><img src=\"assets/img/i.jpg\"\r\n");
      out.write("											alt=\"\"></a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"span3\">\r\n");
      out.write("									<div class=\"thumbnail\">\r\n");
      out.write("										<a class=\"zoomTool\" href=\"product_details.html\"\r\n");
      out.write("											title=\"add to cart\"><span class=\"icon-search\"></span>\r\n");
      out.write("											QUICK VIEW</a> <a href=\"#\" class=\"tag\"></a> <a\r\n");
      out.write("											href=\"product_details.html\"><img src=\"assets/img/g.jpg\"\r\n");
      out.write("											alt=\"\"></a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"span3\">\r\n");
      out.write("									<div class=\"thumbnail\">\r\n");
      out.write("										<a class=\"zoomTool\" href=\"product_details.html\"\r\n");
      out.write("											title=\"add to cart\"><span class=\"icon-search\"></span>\r\n");
      out.write("											QUICK VIEW</a> <a href=\"product_details.html\"><img\r\n");
      out.write("											src=\"assets/img/s.png\" alt=\"\"></a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"item\">\r\n");
      out.write("							<ul class=\"thumbnails\">\r\n");
      out.write("								<li class=\"span3\">\r\n");
      out.write("									<div class=\"thumbnail\">\r\n");
      out.write("										<a class=\"zoomTool\" href=\"product_details.html\"\r\n");
      out.write("											title=\"add to cart\"><span class=\"icon-search\"></span>\r\n");
      out.write("											QUICK VIEW</a> <a href=\"product_details.html\"><img\r\n");
      out.write("											src=\"assets/img/i.jpg\" alt=\"\"></a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"span3\">\r\n");
      out.write("									<div class=\"thumbnail\">\r\n");
      out.write("										<a class=\"zoomTool\" href=\"product_details.html\"\r\n");
      out.write("											title=\"add to cart\"><span class=\"icon-search\"></span>\r\n");
      out.write("											QUICK VIEW</a> <a href=\"product_details.html\"><img\r\n");
      out.write("											src=\"assets/img/f.jpg\" alt=\"\"></a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"span3\">\r\n");
      out.write("									<div class=\"thumbnail\">\r\n");
      out.write("										<a class=\"zoomTool\" href=\"product_details.html\"\r\n");
      out.write("											title=\"add to cart\"><span class=\"icon-search\"></span>\r\n");
      out.write("											QUICK VIEW</a> <a href=\"product_details.html\"><img\r\n");
      out.write("											src=\"assets/img/h.jpg\" alt=\"\"></a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("								<li class=\"span3\">\r\n");
      out.write("									<div class=\"thumbnail\">\r\n");
      out.write("										<a class=\"zoomTool\" href=\"product_details.html\"\r\n");
      out.write("											title=\"add to cart\"><span class=\"icon-search\"></span>\r\n");
      out.write("											QUICK VIEW</a> <a href=\"product_details.html\"><img\r\n");
      out.write("											src=\"assets/img/j.jpg\" alt=\"\"></a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<a class=\"left carousel-control\" href=\"#newProductCar\"\r\n");
      out.write("						data-slide=\"prev\">&lsaquo;</a> <a class=\"right carousel-control\"\r\n");
      out.write("						href=\"#newProductCar\" data-slide=\"next\">&rsaquo;</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row-fluid\">\r\n");
      out.write("				<ul class=\"thumbnails\">\r\n");
      out.write("					<li class=\"span4\">\r\n");
      out.write("						<div class=\"thumbnail\">\r\n");
      out.write("\r\n");
      out.write("							<a class=\"zoomTool\" href=\"product_details.html\"\r\n");
      out.write("								title=\"add to cart\"><span class=\"icon-search\"></span> QUICK\r\n");
      out.write("								VIEW</a> <a href=\"product_details.html\"><img\r\n");
      out.write("								src=\"assets/img/b.jpg\" alt=\"\"></a>\r\n");
      out.write("							<div class=\"caption cntr\">\r\n");
      out.write("								<p>Manicure & Pedicure</p>\r\n");
      out.write("								<p>\r\n");
      out.write("									<strong> $22.00</strong>\r\n");
      out.write("								</p>\r\n");
      out.write("								<h4>\r\n");
      out.write("									<a class=\"shopBtn\" href=\"#\" title=\"add to cart\"> Add to\r\n");
      out.write("										cart </a>\r\n");
      out.write("								</h4>\r\n");
      out.write("								<div class=\"actionList\">\r\n");
      out.write("									<a class=\"pull-left\" href=\"#\">Add to Wish List </a> <a\r\n");
      out.write("										class=\"pull-left\" href=\"#\"> Add to Compare </a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<br class=\"clr\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"span4\">\r\n");
      out.write("						<div class=\"thumbnail\">\r\n");
      out.write("							<a class=\"zoomTool\" href=\"product_details.html\"\r\n");
      out.write("								title=\"add to cart\"><span class=\"icon-search\"></span> QUICK\r\n");
      out.write("								VIEW</a> <a href=\"product_details.html\"><img\r\n");
      out.write("								src=\"assets/img/c.jpg\" alt=\"\"></a>\r\n");
      out.write("							<div class=\"caption cntr\">\r\n");
      out.write("								<p>Manicure & Pedicure</p>\r\n");
      out.write("								<p>\r\n");
      out.write("									<strong> $22.00</strong>\r\n");
      out.write("								</p>\r\n");
      out.write("								<h4>\r\n");
      out.write("									<a class=\"shopBtn\" href=\"#\" title=\"add to cart\"> Add to\r\n");
      out.write("										cart </a>\r\n");
      out.write("								</h4>\r\n");
      out.write("								<div class=\"actionList\">\r\n");
      out.write("									<a class=\"pull-left\" href=\"#\">Add to Wish List </a> <a\r\n");
      out.write("										class=\"pull-left\" href=\"#\"> Add to Compare </a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<br class=\"clr\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"span4\">\r\n");
      out.write("						<div class=\"thumbnail\">\r\n");
      out.write("							<a class=\"zoomTool\" href=\"product_details.html\"\r\n");
      out.write("								title=\"add to cart\"><span class=\"icon-search\"></span> QUICK\r\n");
      out.write("								VIEW</a> <a href=\"product_details.html\"><img\r\n");
      out.write("								src=\"assets/img/a.jpg\" alt=\"\"></a>\r\n");
      out.write("							<div class=\"caption cntr\">\r\n");
      out.write("								<p>Manicure & Pedicure</p>\r\n");
      out.write("								<p>\r\n");
      out.write("									<strong> $22.00</strong>\r\n");
      out.write("								</p>\r\n");
      out.write("								<h4>\r\n");
      out.write("									<a class=\"shopBtn\" href=\"#\" title=\"add to cart\"> Add to\r\n");
      out.write("										cart </a>\r\n");
      out.write("								</h4>\r\n");
      out.write("								<div class=\"actionList\">\r\n");
      out.write("									<a class=\"pull-left\" href=\"#\">Add to Wish List </a> <a\r\n");
      out.write("										class=\"pull-left\" href=\"#\"> Add to Compare </a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<br class=\"clr\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!--\r\n");
      out.write("	Featured Products\r\n");
      out.write("	-->\r\n");
      out.write("		<div class=\"well well-small\">\r\n");
      out.write("			<h3>\r\n");
      out.write("				<a class=\"btn btn-mini pull-right\" href=\"products.html\"\r\n");
      out.write("					title=\"View more\">VIew More<span class=\"icon-plus\"></span></a>\r\n");
      out.write("				Featured Products\r\n");
      out.write("			</h3>\r\n");
      out.write("			<hr class=\"soften\" />\r\n");
      out.write("			<div class=\"row-fluid\">\r\n");
      out.write("				<ul class=\"thumbnails\">\r\n");
      out.write("					<li class=\"span4\">\r\n");
      out.write("						<div class=\"thumbnail\">\r\n");
      out.write("							<a class=\"zoomTool\" href=\"product_details.html\"\r\n");
      out.write("								title=\"add to cart\"><span class=\"icon-search\"></span> QUICK\r\n");
      out.write("								VIEW</a> <a href=\"product_details.html\"><img\r\n");
      out.write("								src=\"assets/img/d.jpg\" alt=\"\"></a>\r\n");
      out.write("							<div class=\"caption\">\r\n");
      out.write("								<h5>Manicure & Pedicure</h5>\r\n");
      out.write("								<h4>\r\n");
      out.write("									<a class=\"defaultBtn\" href=\"product_details.html\"\r\n");
      out.write("										title=\"Click to view\"><span class=\"icon-zoom-in\"></span></a> <a\r\n");
      out.write("										class=\"shopBtn\" href=\"#\" title=\"add to cart\"><span\r\n");
      out.write("										class=\"icon-plus\"></span></a> <span class=\"pull-right\">$22.00</span>\r\n");
      out.write("								</h4>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"span4\">\r\n");
      out.write("						<div class=\"thumbnail\">\r\n");
      out.write("							<a class=\"zoomTool\" href=\"product_details.html\"\r\n");
      out.write("								title=\"add to cart\"><span class=\"icon-search\"></span> QUICK\r\n");
      out.write("								VIEW</a> <a href=\"product_details.html\"><img\r\n");
      out.write("								src=\"assets/img/e.jpg\" alt=\"\"></a>\r\n");
      out.write("							<div class=\"caption\">\r\n");
      out.write("								<h5>Manicure & Pedicure</h5>\r\n");
      out.write("								<h4>\r\n");
      out.write("									<a class=\"defaultBtn\" href=\"product_details.html\"\r\n");
      out.write("										title=\"Click to view\"><span class=\"icon-zoom-in\"></span></a> <a\r\n");
      out.write("										class=\"shopBtn\" href=\"#\" title=\"add to cart\"><span\r\n");
      out.write("										class=\"icon-plus\"></span></a> <span class=\"pull-right\">$22.00</span>\r\n");
      out.write("								</h4>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"span4\">\r\n");
      out.write("						<div class=\"thumbnail\">\r\n");
      out.write("							<a class=\"zoomTool\" href=\"product_details.html\"\r\n");
      out.write("								title=\"add to cart\"><span class=\"icon-search\"></span> QUICK\r\n");
      out.write("								VIEW</a> <a href=\"product_details.html\"><img\r\n");
      out.write("								src=\"assets/img/f.jpg\" alt=\"\" /></a>\r\n");
      out.write("							<div class=\"caption\">\r\n");
      out.write("								<h5>Manicure & Pedicure</h5>\r\n");
      out.write("								<h4>\r\n");
      out.write("									<a class=\"defaultBtn\" href=\"product_details.html\"\r\n");
      out.write("										title=\"Click to view\"><span class=\"icon-zoom-in\"></span></a> <a\r\n");
      out.write("										class=\"shopBtn\" href=\"#\" title=\"add to cart\"><span\r\n");
      out.write("										class=\"icon-plus\"></span></a> <span class=\"pull-right\">$22.00</span>\r\n");
      out.write("								</h4>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"well well-small\">\r\n");
      out.write("			<a class=\"btn btn-mini pull-right\" href=\"#\">View more <span\r\n");
      out.write("				class=\"icon-plus\"></span></a> Popular Products\r\n");
      out.write("		</div>\r\n");
      out.write("		<hr>\r\n");
      out.write("		<div class=\"well well-small\">\r\n");
      out.write("			<a class=\"btn btn-mini pull-right\" href=\"#\">View more <span\r\n");
      out.write("				class=\"icon-plus\"></span></a> Best selling Products\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/user/index.jsp(13,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      // /WEB-INF/views/user/index.jsp(13,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/user/index.jsp(13,5) '${categorys }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${categorys }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("						<li><a href=\"/san-pham/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"><span\r\n");
            out.write("								class=\"icon-circle-blank\"></span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></li>\r\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/user/index.jsp(89,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("item");
      // /WEB-INF/views/user/index.jsp(89,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/user/index.jsp(89,6) '${slides }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${slides }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/user/index.jsp(89,6) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVarStatus("index");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("							");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("\r\n");
            out.write("							");
            if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("							<img style=\"width: 100%\"\r\n");
            out.write("								src=\"");
            if (_jspx_meth_c_005furl_005f0(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\"\r\n");
            out.write("								alt=\"bootstrap ecommerce templates\">\r\n");
            out.write("							<div class=\"carousel-caption\">\r\n");
            out.write("								<h4>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.caption }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h4>\r\n");
            out.write("								<p>\r\n");
            out.write("									<span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.content }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("								</p>\r\n");
            out.write("							</div>\r\n");
            out.write("					</div>\r\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/views/user/index.jsp(90,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${index.first }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<div class=\"item active\">\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/views/user/index.jsp(94,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not index.first }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<div class=\"item\">\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/views/user/index.jsp(98,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("/assets/user/img/slide/${item.img }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
